### ISSUE TITLE
Add daytrade counter / PDT pre-check to API

### ISSUE THREAD

**Issue by evanhft** [alpacahq/Alpaca-API#11]

**Comment by codebeaulieu** [comment]
I'm increasingly wishing I had this feature. Will be very helpful for decision making.

**Comment by mingchang** [comment]
This would be quite useful, since I'm assuming that if you had 3 day-trades already this week, then the 4th buy order (if issued first) wouldn't get rejected, and it would only be the sell order that gets rejected (since the sell order actually triggers the PDT).

(Hopefully someone can confirm if this assumption is correct)

My use case would be to get this count from API, and not even initiate the 4th buy order, since not being able to sell the stock until 1-5 business days later, when the PDT limitation is past, would cause undue risk to the portfolio.

**Comment by mingchang** [comment]
After some more digging I'm seeing the "daytrade_count": 0, flag returned in the get_account() API call. So it seems like this exists now, perhaps this issue just hasn't been updated in a while?

**Comment by ZippeyKeys12** [comment]
As @mingchang pointed out, there's the `daytrade_count` value
