### ISSUE TITLE
api.get_calendar 404 url not found

### ISSUE THREAD

**Issue by russelldouglas** [alpacahq/Alpaca-API#141]
**Describe the bug**
I'm running a script I found online for paper trading on alpaca. It has a bit where that says calendar = api.get_calendar(start=today_string, end=today_string)[0]
For some reason, this throws the error "404 Client Error: Not Found for url: https://paper-api.alpaca.markets//v2/calendar?start=2020-12-08&end=2020-12-08"
Can anyone help me with this?

Link to the original place I found the code
[https://medium.com/automation-generation/build-a-day-trading-algorithm-and-run-it-in-the-cloud-for-free-805450150668](url)

**Comment by kalmant** [comment]
Hi there,

As the error suggests, you're trying to access an url that does not exist. This is because there are two `/`s in the url before `v2`, so
```
https://paper-api.alpaca.markets//v2/calendar?start=2020-12-08&end=2020-12-08
```
instead of
```
https://paper-api.alpaca.markets/v2/calendar?start=2020-12-08&end=2020-12-08
```

This is because the `base_url` you set has a trailing slash.
Also please make sure not to leak your api secret anywhere (i.e. it's clearly readable in this picture).

**Comment by russelldouglas** [comment]
Awesome! I can't believe I didn't see that! Thanks!

Also thanks for notifying me that my key was visible here, I didn't realize that!
