### ISSUE TITLE
Offer account balance history endpoint.

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/Alpaca-API#21]
It appears the the web portal calls an endpoint that tracks account history. But I belive that endpoint is unavailable to the public. This feature would be good for tracking performance over time and visualizing account balances in our own UI's.

**Comment by corakwue** [comment]
+1 

To properly track performance, API need the following endpoints:
- Order history (API supports this)
- Account transfers (i.e. deposits & withdrawals) (**note:** Available but not exposed via API)
- Dividend history paid into account (no available AFAIK)

**Comment by dbelwood** [comment]
+1

This would help me close the loop on automated ledgering for my trading

**Comment by ViridianHawk** [comment]
+1

This feature is pretty important to in order to assess our strategy's performance -- calculating beta, alpha, Sharpe ratio, underwater map, etc.

Agree with @corakwue -- in addition to a _historical EOD account balance_ API endpoint, it'd be important to have a _history of deposits/withdrawals_ endpoint as well in order to properly assess performance.

**Comment by umitanuki** [comment]
Agree, those are important to help not just algo performance but also building custom UI dashboard.
