### ISSUE TITLE
list_orders() 502 error

### ISSUE THREAD

**Issue by JonBonJoVicious** [alpacahq/Alpaca-API#25]
On 2019-01-25, after running the code for several days, api.list_orders() generated a 502 error for a paper trading account. I have tried the following code on several machines on several networks. Same error. all other api functions seem to be working. I have no idea what is going on. Any help would be greatly appreciated.
````import alpaca_trade_api as tradeapi
import numpy as np
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
import pandas_datareader.data as web
import time
from itertools import cycle
from apscheduler.schedulers.blocking import BlockingScheduler
from pandas.tseries.offsets import *
global key_id
global secret_key
global base_url

key_id='REDACTED'
secret_key='REDACTED'
base_url='https://paper-api.alpaca.markets'#Paper Trading

api = tradeapi.REST(key_id=key_id, secret_key=secret_key,base_url=base_url)
api.list_orders()#{HTTPError: 502 Server Error: Bad Gateway for url: https://paper-api.alpaca.markets/v1/orders}
```

**Comment by umitanuki** [comment]
Sorry for being late here. We sometimes see this error when one of the positions is delisted or symbol changes which results in missing reference price. This is particularly problematic in paper trading side right now, since we are not processing corporate actions as much as live side. We keep improving the experience around this, and will keep you updated.
