### ISSUE TITLE
Option Open Interest

### ISSUE THREAD

**Issue by Chacoon3** [alpacahq/Alpaca-API#261]
**Is your feature request related to a problem? Please describe.**
Currently the option open interest is available only through certain endpoints which belong to the trading API. Endpoints of the market data API do not provide option interest in the response (i.e., the option snapshot object). 

**Describe the solution you'd like**
I hope that the snapshot endpoint and the option chain endpoint can both provide option interest information. Preferably making the option open interest as a field of the option snapshot object. 

This is useful since I can get the information of an option using just one data API call instead of one data API call and one trading API call.

**Additional context**
Providing option interest is a common practice of option data vendors.

**Comment by umitanuki** [comment]
Open interest doesn't change throughout the day, which is why it is on the assets API than snapshots. Snapshots API is called very frequently and saving extra bytes that don't need to be in the payload would be a huge bandwidth saving. I hear you that it would be "convenient" from one point of view, but we have seen others expressing the current way is better, so it is not an easy decision.

**Comment by Chacoon3** [comment]
> Open interest doesn't change throughout the day, which is why it is on the assets API than snapshots. Snapshots API is called very frequently and saving extra bytes that don't need to be in the payload would be a huge bandwidth saving. I hear you that it would be "convenient" from one point of view, but we have seen others expressing the current way is better, so it is not an easy decision.

Thanks for replying. I overlooked the frequency at which the open interest is updated. Given that, I agree with the current API design.
